#!/bin/bash

cat << EOF

 Congratulations - you've compiled Guild AI!

 Run tests by running 'make test'

 Run 'scripts/guild-dev' directly or create a symbolic link
 to it somewhere on your path.

EOF
