#!/bin/bash

if [ ! -f /var/www/html ]; then
  cd /var/www/ && ln -s /root/volumes/source.ml/web.ml/sparkafterdark/html
fi

if [ ! -f /etc/apache2/apache2.conf ]; then
  cd /etc/apache2/ && ln -s /root/volumes/source.ml/web.ml/sparkafterdark/config/apache2.conf
fi

if [ ! -f /etc/apache2/sites-enabled/www.conf ]; then
  cd /etc/apache2/sites-enabled/ && ln -s /root/volumes/web.ml/sparkafterdark/config/www.conf
fi

if [ ! -f /etc/apache2/sites-enabled/sparkafterdark.conf ]; then
  cd /etc/apache2/sites-enabled/ && ln -s /root/volumes/web.ml/sparkafterdark/config/sparkafterdark.conf
fi

a2ensite www.conf
a2ensite sparkafterdark.conf

source /etc/apache2/envvars

service apache2 start

tail -f $APACHE_LOG_DIR/error.log 
