FROM python:3.6-slim

COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt
COPY DoppelgangerModel.py /app
COPY pairwise_top_25_v2.json pairwise_top_25.json

ENV MODEL_NAME DoppelgangerModel 
ENV API_TYPE REST
ENV SERVICE_TYPE MODEL
ENV PERSISTENCE 0

EXPOSE 5000 

CMD exec seldon-core-microservice $MODEL_NAME $API_TYPE --service-type $SERVICE_TYPE --persistence $PERSISTENCE
