#!/bin/bash

if [ ! -f ~/data ]; then
  cd ~ && ln -s /root/volumes/source.ml/keyvalue.ml/redis/data
  chmod a+w data/dump.rdb
fi

cd ~/webdis
./webdis webdis.json &

cd ~
redis-server config/redis.conf
