/*
 *
 * EnvironmentsPage constants
 *
 */

export const DEFAULT_ACTION = 'app/EnvironmentsListPage/DEFAULT_ACTION';
export const LOAD_ENVIRONMENTS_REQUEST = 'app/Environments/LOAD_ENVIRONMENTS_REQUEST';
export const LOAD_ENVIRONMENTS_SUCCESS = 'app/Environments/LOAD_ENVIRONMENTS_SUCCESS';
export const LOAD_ENVIRONMENTS_ERROR = 'app/Environments/LOAD_ENVIRONMENTS_ERROR';
export const CREATE_ENVIRONMENT_REQUEST = 'app/Environments/CREATE_ENVIRONMENT_REQUEST';
export const CREATE_ENVIRONMENT_SUCCESS = 'app/Environments/CREATE_ENVIRONMENT_SUCCESS';
export const CREATE_ENVIRONMENT_ERROR = 'app/Environments/CREATE_ENVIRONMENT_ERROR';
export const DELETE_ENVIRONMENT_REQUEST = 'app/Environments/DELETE_ENVIRONMENT_REQUEST';
export const DELETE_ENVIRONMENT_SUCCESS = 'app/Environments/DELETE_ENVIRONMENT_SUCCESS';
export const DELETE_ENVIRONMENT_ERROR = 'app/Environments/DELETE_ENVIRONMENT_ERROR';
export const GET_ENVIRONMENT_REQUEST = 'app/Environments/GET_ENVIRONMENT_REQUEST';
export const GET_ENVIRONMENT_SUCCESS = 'app/Environments/GET_ENVIRONMENT_SUCCESS';
export const GET_ENVIRONMENT_ERROR = 'app/Environments/GET_ENVIRONMENT_ERROR';
export const EDIT_ENVIRONMENT_REQUEST = 'app/Environments/EDIT_ENVIRONMENT_REQUEST';
export const EDIT_ENVIRONMENT_SUCCESS = 'app/Environments/EDIT_ENVIRONMENT_SUCCESS';
export const EDIT_ENVIRONMENT_ERROR = 'app/Environments/EDIT_ENVIRONMENT_ERROR';
