#!/bin/bash -eu

if [ "${TRACE_EXEC:-}" = "1" ]; then
    set -x
fi

realpath() {
    if [ "$(uname -s)" = "Darwin" ]; then
        perl -e 'use Cwd "abs_path";print abs_path(shift)' "$1"
    else
        readlink -f "$1"
    fi
}

ERL=$(which erl || true)
if [ "$ERL" = "" ]; then
    echo "ERROR: Cannot find Erlang, which is required to run Guild" >&2
    exit 1
fi

REAL_ERL=$(realpath $ERL)
export ROOTDIR=${REAL_ERL%/*/*}

read -r -a ERTS_PATHS <<< "$(echo $ROOTDIR/erts-*/bin)"
export BINDIR=${ERTS_PATHS[*]: -1}

SCRIPT=$(realpath $0)
SCRIPTDIR=${SCRIPT%/*}

export GUILD_GIT_COMMIT=`cd $SCRIPTDIR && git log -1 --oneline | cut -d' ' -f1`
export ERL_LIBS=$SCRIPTDIR/../build/default/lib
export EMU=beam
export PROGNAME=$0
export ERL_CRASH_DUMP=/dev/null

exec $BINDIR/erlexec +B -boot start_clean -noshell -run guild main -extra "$@"
