#!/bin/bash

if [ ! -f $AIRFLOW_HOME/dags ]; then
  cd $AIRFLOW_HOME && ln -s /root/volumes/source.ml/scheduler.ml/airflow/dags 
fi

if [ ! -f $AIRFLOW_HOME/triggers ]; then
  cd $AIRFLOW_HOME && ln -s /root/volumes/source.ml/scheduler.ml/airflow/triggers
fi

/usr/local/bin/dockerd

mysql --host=sql-mysql-master --port=3306 --user=root --password=password -e "CREATE DATABASE IF NOT EXISTS airflow"
sleep 2

# TODO:  Don't re-init upon process restart
airflow initdb
sleep 2 

# TODO:  Separate these out into separate containers - perhaps in same pod
airflow flower &

airflow webserver &

airflow worker &

airflow scheduler 
