#!/bin/bash

if [ ! -f $AIRFLOW_HOME/dags ]; then
  cd $AIRFLOW_HOME && ln -s /root/volumes/source.ml/scheduler.ml/airflow/dags 
fi

if [ ! -f $AIRFLOW_HOME/triggers ]; then
  cd $AIRFLOW_HOME && ln -s /root/volumes/source.ml/scheduler.ml/airflow/triggers
fi

/usr/local/bin/dockerd

# Start Airflow
mysql --host=mysql-master --port=3306 --user=root --password=password -e "CREATE DATABASE IF NOT EXISTS airflow"
sleep 2

airflow initdb
sleep 2 

#/root/triggers/github_webhook &

airflow flower &

airflow webserver &

airflow worker &

airflow scheduler 
