apiVersion: v1
kind: Service
metadata:
  name: mysql-master
spec:
  type: NodePort 
  ports:
    # the port that this service should serve on
  - name: mysql-native 
    port: 3306 
    targetPort: 3306
  selector:
    name: mysql-master
