#!/bin/bash

echo '...Setting up Database...'
mysql --host=$MYSQL_MASTER_SERVICE_HOST --port=$MYSQL_MASTER_SERVICE_PORT_MYSQL_NATIVE \
  --user=root --password=password -e 'CREATE DATABASE IF NOT EXISTS airpal'

echo '...Initializing AirPal Service...'
cd ~/airpal
java -Duser.timezone=UTC \
  -cp build/libs/airpal-*-all.jar com.airbnb.airpal.AirpalApplication db migrate /root/config/reference.yml

echo '...Starting AirPal Service...'
java -server \
     -Duser.timezone=UTC \
     -cp build/libs/airpal-*-all.jar com.airbnb.airpal.AirpalApplication server /root/config/reference.yml
