#!/bin/bash

cd ~

# Set Internal File Separator (IFS) to ':'
( IFS=:
  for test_pathname in $TEST_PATHNAMES; do
      /root/apache-jmeter-3.0/bin/jmeter.sh -n -t $test_pathname &
      echo "Executed test $test_pathname"
  done
)

tail -f ~/jmeter.log
