apiVersion: v1
kind: Service
metadata:
  name: cassandra 
spec:
  type: NodePort 
  ports:
  - name: jmx
    port: 7199 
    targetPort: 7199
  - name: native
    port: 9042
    targetPort: 9042
  - name: thrift
    port: 9160
    targetPort: 9160
  - name: gossip
    port: 7000
    targetPort: 7000
  selector:
    name: cassandra
