FROM fluxcapacitor/package-spark-2.1.0:master

WORKDIR /root

COPY run.master run
COPY demos/ demos/

# Expose Spark Master Port for Web Admin UI
EXPOSE 6060

# Expose Spark Master Port for REST API
EXPOSE 6066

# Expose Spark Master Port for Spark Workers
EXPOSE 7077

# Expose Spark Job Admin Ports
EXPOSE 4040 4041 4042 4043 4044

CMD ["supervise", "."]
