# config file version
apiVersion: 1

# list of datasources to insert/update depending
# whats available in the datbase
datasources:
  # <string, required> name of the datasource. Required
  - name: Prometheus
    # <string, required> datasource type. Required
    type: prometheus
    # <string, required> access mode. direct or proxy. Required
    access: proxy 
    # <int> org id. will default to org_id 1 if not specified
    orgId: 1
    # <string> url
    url: http://localhost:9090
    # <bool> mark as default datasource. Max one per org
    isDefault: true
    # <map> fields that will be converted to json and stored in json_data
    jsonData:
      timeInterval: 1s
    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: true
