#!/bin/bash

echo 'Usage:'
echo '  down <tag>'
echo ''
echo 'Example:'
echo '  down v1.1.0'

###################################
# Dashboards and Metrics
###################################
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/dashboard.ml/turbine-deploy.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/dashboard.ml/turbine-svc.yaml

kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/dashboard.ml/hystrix-deploy.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/dashboard.ml/hystrix-svc.yaml

kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/dashboard.ml/weavescope/weavescope.yaml

###################################
# Model Training and Data Services
###################################
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/sql.ml/mysql-master-deploy.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/sql.ml/mysql-master-svc.yaml

kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/hdfs.ml/namenode-deploy.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/hdfs.ml/namenode-svc.yaml

kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/apachespark.ml/master-deploy.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/apachespark.ml/master-svc.yaml

kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/apachespark.ml/worker-deploy.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/apachespark.ml/worker-hpa.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/apachespark.ml/worker-svc.yaml

kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/metastore.ml/metastore-deploy.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/metastore.ml/metastore-svc.yaml

kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/jupyterhub.ml/jupyterhub-deploy.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/jupyterhub.ml/jupyterhub-svc.yaml

kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/presto.ml/presto-master-deploy.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/presto.ml/presto-master-svc.yaml

kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/presto.ml/presto-worker-deploy.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/presto.ml/presto-worker-hpa.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/presto.ml/presto-worker-svc.yaml

kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/presto.ml/presto-ui-deploy.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/presto.ml/presto-ui-svc.yaml

kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/web.ml/home-deploy.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/web.ml/home-svc.yaml

kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/scheduler.ml/airflow-deploy.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/scheduler.ml/airflow-svc.yaml

kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/zeppelin.ml/zeppelin-deploy.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/zeppelin.ml/zeppelin-svc.yaml

###################################
# Model Prediction Services
###################################
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/prediction.ml/java-deploy.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/prediction.ml/java-svc.yaml

kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/prediction.ml/keyvalue-deploy.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/prediction.ml/keyvalue-svc.yaml

kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/prediction.ml/pmml-deploy.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/prediction.ml/pmml-svc.yaml

kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/prediction.ml/python-deploy.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/prediction.ml/python-svc.yaml

kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/prediction.ml/tensorflow-deploy.yaml
kubectl delete -f https://raw.githubusercontent.com/fluxcapacitor/pipeline/$1/prediction.ml/tensorflow-svc.yaml
