apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scheduler-airflow
  labels:
    app: scheduler-airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-airflow
  template:
    metadata:
      labels:
        app: scheduler-airflow
    spec:
      containers:
      - name: scheduler-airflow
        image: docker.io/fluxcapacitor/scheduler-airflow:master
        resources:
          limits:
            cpu: 1000m
            memory: 5000Mi
          requests:
            cpu: 100m
            memory: 500Mi
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: SPARK_MASTER
          value: spark://apachespark-master-2-1-0:7077
        - name: SPARK_SUBMIT_ARGS
          value: ""
        ports:
        - containerPort: 8080
        - containerPort: 5000
        - containerPort: 5555
        - containerPort: 8793
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: kube-config-secret-volume
            readOnly: true
            mountPath: /root/.kube
          - name: hdfs-config-volume
            mountPath: /root/hadoop-2.7.2/etc/hadoop
          - name: spark-config-volume
            mountPath: /root/spark-2.1.0-bin-fluxcapacitor/conf
          - name: airflow-config-volume
            mountPath: /root/config-map/airflow
          - name: git-volume
            mountPath: /root/volumes
        securityContext:
          privileged: true
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - name: kube-config-secret-volume
          secret:
            secretName: kube-config-secret
        - name: hdfs-config-volume
          configMap:
            name: hdfs-config
        - name: spark-config-volume
          configMap:
            name: spark-config
        - name: airflow-config-volume
          configMap:
            name: airflow-config
        - name: git-volume
          gitRepo:
            repository: "https://github.com/fluxcapacitor/source.ml"
            revision: "master"
