apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prediction-jvm
  labels:
    app: prediction-jvm
    hystrix.enabled: "true"
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: prediction-jvm
  template:
    metadata:
      labels:
        app: prediction-jvm
        hystrix.enabled: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/prometheus"
        prometheus.io/port: "9040"
    spec:
      containers:
      - name: prediction-jvm
        image: docker.io/fluxcapacitor/prediction-jvm:v1.2.0
        resources:
          limits:
            cpu: 4000m
            memory: 2000Mi
          requests:
            cpu: 400m
            memory: 200Mi 
        imagePullPolicy: "Always"
        env:
        ports:
        - containerPort: 9040
        volumeMounts:
          - name: git-volume
            mountPath: /root/volumes
      volumes:
        - name: git-volume
          gitRepo:
            repository: "https://github.com/fluxcapacitor/source.ml.git"
            revision: "v1.2.0"
