apiVersion: v1
kind: ReplicationController
metadata:
  name: prediction-keyvalue
  labels:
    app: prediction-keyvalue
    hystrix.enabled: "true"
spec:
  replicas: 1
  selector:
    name: prediction-keyvalue
  template:
    metadata:
      labels:
        name: prediction-keyvalue
        hystrix.enabled: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/prometheus"
        prometheus.io/port: "9040"
    spec:
      containers:
      - name: prediction-keyvalue
        image: docker.io/fluxcapacitor/prediction-keyvalue
        imagePullPolicy: "Always"
        env:
        ports:
        - containerPort: 9040
#      nodeSelector:
#        nodetype: prediction
#        livenessProbe:
#          httpGet:
#            path: "/health"
#            port: 9040
#          initialDelaySeconds: 300 
#        readinessProbe:
#          httpGet:
#            path: "/health"
#            port: 9040
#          initialDelaySeconds: 30 
