apiVersion: v1
kind: ReplicationController
metadata:
  name: prediction-pmml
  labels:
    app: prediction-pmml
    hystrix.enabled: "true"
spec:
  replicas: 1
  selector:
    name: prediction-pmml
  template:
    metadata:
      labels:
        name: prediction-pmml
        hystrix.enabled: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/prometheus"
        prometheus.io/port: "9040"
    spec:
      containers:
      - name: prediction-pmml
        image: docker.io/fluxcapacitor/prediction-pmml:v1.0.0
        imagePullPolicy: "Always"
        env:
        ports:
        - containerPort: 9040
        volumeMounts:
          - name: git-volume
            mountPath: /root/volumes
      volumes:
        - name: git-volume
          gitRepo:
            repository: "https://github.com/fluxcapacitor/source.ml.git"
            revision: "v1.0.0"
      nodeSelector:
        prediction: "true"
