apiVersion: v1
kind: Service
metadata:
  name: prediction-python
  labels:
    app: prediction-python
#  annotations:
#    dns.alpha.kubernetes.io/external: prediction-python.your.domain.com
spec:
  type: LoadBalancer
  ports:
  - name: model-server
    port: 80
    targetPort: 9876
  - name: bundle-server
    port: 81
    targetPort: 8000
  - name: scala-server
    port: 9040
    targetPort: 9040
  - name: not-sure
    port: 9000
    targetPort: 9000
  selector:    
    app: prediction-python
