apiVersion: v1
kind: Service
metadata:
  name: prediction-python
  labels:
    app: prediction-python
    hystrix.enabled: "true"
#  annotations:
#    dns.alpha.kubernetes.io/external: prediction-python.your.domain.com
spec:
  type: LoadBalancer
  ports:
  - name: prediction-python
    port: 80 
    targetPort: 9040 
    port: 81
    targetPort: 9876
  selector:    
    app: prediction-python
    hystrix.enabled: "true" 
