apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prediction-python
  labels:
    app: prediction-python
    hystrix.enabled: "true"
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: prediction-python
  template:
    metadata:
      labels:
#        name: prediction-java
        app: prediction-python
        hystrix.enabled: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/prometheus"
        prometheus.io/port: "9040"
    spec:
      containers:
      - name: prediction-python
        image: docker.io/fluxcapacitor/prediction-python:master
        resources:
          limits:
            cpu: 1000m
            memory: 5000Mi
          requests:
            cpu: 200m
            memory: 200Mi 
        imagePullPolicy: "Always"
        env:
        ports:
        - containerPort: 9040
        volumeMounts:
          - name: git-volume
            mountPath: /root/volumes
      volumes:
        - name: git-volume
          gitRepo:
            repository: "https://github.com/fluxcapacitor/source.ml.git"
            revision: "master"

