apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prediction-python
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: prediction-python
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 95
