apiVersion: v1
kind: Service
metadata:
  name: prediction-tensorflow-gpu
  labels:
    app: prediction-tensorflow-gpu
#    hystrix.enabled: "true"
#      dns: route53
#    annotations:
#      domainName: prediction-tensorflow.your.domain.com
spec:
  type: LoadBalancer
  ports:
  - name: http-model-server 
    port: 80 
    targetPort: 9876 
  - name: grpc-tensorflow-serving
    port: 9000
    targetPort: 9000
  - name: http-netflixoss
    port: 9040
    targetPort: 9040
  selector:
    app: prediction-tensorflow-gpu
#    hystrix.enabled: "true"
