#!/bin/bash

start_hystrix_dashboard () {
    export JAVA_MAX_MEM_RATIO=85
    export JAVA_OPTIONS="$(sysutils/jvm-limits.sh)"
    echo ""
    echo "JAVA_OPTIONS=$JAVA_OPTIONS"
    echo ""
    echo "Starting JVM-based Dashboard Server..."
    echo ""

    cd /root/hystrix-dashboard/ && ../gradlew appRun
}

start_hystrix_dashboard
