#!/bin/bash

start_hystrix_dashboard () {
    source sysutils/container-limits.sh
    export JAVA_MAX_MEM_RATIO=85
    export JAVA_OPTIONS="$(sysutils/jvm-limits.sh)"
    echo ""
    echo "JAVA_OPTIONS=$JAVA_OPTIONS"
    echo ""
    echo "Starting JVM-based Dashboard Server..."
    echo ""

    java -jar /root/jetty-0.4.7.RC0.jar --path /hystrix-dashboard --port $HYSTRIX_DASHBOARD_PORT /root/hystrix-dashboard/build/libs/hystrix-dashboard-0.1.0-dev.0.uncommitted.war
}

start_hystrix_dashboard
