#!/bin/bash

#./start-all-prediction-services.sh

cd $MYAPPS_HOME/serving/prediction

java -Dspring.profiles.active=$SPRING_PROFILES_ACTIVE -Djava.security.egd=file:/dev/./urandom -cp lib/codegen-spark-1-6-1_2.10-1.0.jar -jar ~/sbt/bin/sbt-launch.jar "run-main com.advancedspark.serving.prediction.PredictionServiceMain"

#tail -f $LOGS_HOME/serving/prediction/prediction.log
