apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: presto-worker
  labels:
    app: presto-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presto-worker
  template:
    metadata:
      labels:
        app: presto-worker
    spec:
      containers:
      - name: presto-worker
        image: docker.io/fluxcapacitor/presto-worker-0.167:master
        resources:
          limits:
            cpu: 1000m
            memory: 10000Mi
          requests:
            cpu: 100m
            memory: 1000Mi
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 7060
        volumeMounts:
          - name: presto-catalog-volume
            mountPath: /root/presto-server-0.167/etc/catalog
      volumes:
        - name: presto-catalog-volume
          configMap:
            name: presto-catalog
