apiVersion: v1
kind: Service
metadata:
  name: presto-ui
  labels:
    app: presto-ui 
  annotations:
    dns.alpha.kubernetes.io/external: presto.your.domain.com
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 4125
  selector:
    app: presto-ui 
