apiVersion: v1
kind: ReplicationController
metadata:
  name: presto-ui 
  labels:
    app: presto-ui
spec:
  replicas: 1
  selector:
    name: presto-ui 
  template:
    metadata:
      labels:
        name: presto-ui 
    spec:
      containers:
      - name: presto-ui 
        image: docker.io/fluxcapacitor/presto-ui
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 4125
