apiVersion: v1
kind: Service
metadata:
  name: presto-ui
  labels:
    app: presto-ui 
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 4125
  selector:
    app: presto-ui 
