apiVersion: v1
kind: ReplicationController
metadata:
  name: api-gateway 
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    name: api-gateway
  template:
    metadata:
      labels:
        name: api-gateway 
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: api-gateway 
        image: docker.io/fluxcapacitor/api-gateway
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        ports:
        - containerPort: 8080 
      nodeSelector:
        prediction: "true"
