# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/framework/op_gen_overrides.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensorflow/core/framework/op_gen_overrides.proto',
  package='tensorflow',
  syntax='proto3',
  serialized_pb=_b('\n0tensorflow/core/framework/op_gen_overrides.proto\x12\ntensorflow\x1a*tensorflow/core/framework/attr_value.proto\"\xa7\x03\n\rOpGenOverride\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04skip\x18\x02 \x01(\x08\x12\x0c\n\x04hide\x18\x03 \x01(\x08\x12\x11\n\trename_to\x18\x04 \x01(\t\x12\r\n\x05\x61lias\x18\x05 \x03(\t\x12;\n\x0c\x61ttr_default\x18\x06 \x03(\x0b\x32%.tensorflow.OpGenOverride.AttrDefault\x12\x35\n\x0b\x61ttr_rename\x18\x07 \x03(\x0b\x32 .tensorflow.OpGenOverride.Rename\x12\x36\n\x0cinput_rename\x18\x08 \x03(\x0b\x32 .tensorflow.OpGenOverride.Rename\x12\x37\n\routput_rename\x18\t \x03(\x0b\x32 .tensorflow.OpGenOverride.Rename\x1a\x41\n\x0b\x41ttrDefault\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.tensorflow.AttrValue\x1a\"\n\x06Rename\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\"7\n\x0eOpGenOverrides\x12%\n\x02op\x18\x01 \x03(\x0b\x32\x19.tensorflow.OpGenOverrideb\x06proto3')
  ,
  dependencies=[tensorflow_dot_core_dot_framework_dot_attr__value__pb2.DESCRIPTOR,])




_OPGENOVERRIDE_ATTRDEFAULT = _descriptor.Descriptor(
  name='AttrDefault',
  full_name='tensorflow.OpGenOverride.AttrDefault',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tensorflow.OpGenOverride.AttrDefault.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='tensorflow.OpGenOverride.AttrDefault.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=496,
)

_OPGENOVERRIDE_RENAME = _descriptor.Descriptor(
  name='Rename',
  full_name='tensorflow.OpGenOverride.Rename',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='tensorflow.OpGenOverride.Rename.from', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to', full_name='tensorflow.OpGenOverride.Rename.to', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=532,
)

_OPGENOVERRIDE = _descriptor.Descriptor(
  name='OpGenOverride',
  full_name='tensorflow.OpGenOverride',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tensorflow.OpGenOverride.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skip', full_name='tensorflow.OpGenOverride.skip', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hide', full_name='tensorflow.OpGenOverride.hide', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rename_to', full_name='tensorflow.OpGenOverride.rename_to', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alias', full_name='tensorflow.OpGenOverride.alias', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attr_default', full_name='tensorflow.OpGenOverride.attr_default', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attr_rename', full_name='tensorflow.OpGenOverride.attr_rename', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_rename', full_name='tensorflow.OpGenOverride.input_rename', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_rename', full_name='tensorflow.OpGenOverride.output_rename', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_OPGENOVERRIDE_ATTRDEFAULT, _OPGENOVERRIDE_RENAME, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=532,
)


_OPGENOVERRIDES = _descriptor.Descriptor(
  name='OpGenOverrides',
  full_name='tensorflow.OpGenOverrides',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='op', full_name='tensorflow.OpGenOverrides.op', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=534,
  serialized_end=589,
)

_OPGENOVERRIDE_ATTRDEFAULT.fields_by_name['value'].message_type = tensorflow_dot_core_dot_framework_dot_attr__value__pb2._ATTRVALUE
_OPGENOVERRIDE_ATTRDEFAULT.containing_type = _OPGENOVERRIDE
_OPGENOVERRIDE_RENAME.containing_type = _OPGENOVERRIDE
_OPGENOVERRIDE.fields_by_name['attr_default'].message_type = _OPGENOVERRIDE_ATTRDEFAULT
_OPGENOVERRIDE.fields_by_name['attr_rename'].message_type = _OPGENOVERRIDE_RENAME
_OPGENOVERRIDE.fields_by_name['input_rename'].message_type = _OPGENOVERRIDE_RENAME
_OPGENOVERRIDE.fields_by_name['output_rename'].message_type = _OPGENOVERRIDE_RENAME
_OPGENOVERRIDES.fields_by_name['op'].message_type = _OPGENOVERRIDE
DESCRIPTOR.message_types_by_name['OpGenOverride'] = _OPGENOVERRIDE
DESCRIPTOR.message_types_by_name['OpGenOverrides'] = _OPGENOVERRIDES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OpGenOverride = _reflection.GeneratedProtocolMessageType('OpGenOverride', (_message.Message,), dict(

  AttrDefault = _reflection.GeneratedProtocolMessageType('AttrDefault', (_message.Message,), dict(
    DESCRIPTOR = _OPGENOVERRIDE_ATTRDEFAULT,
    __module__ = 'tensorflow.core.framework.op_gen_overrides_pb2'
    # @@protoc_insertion_point(class_scope:tensorflow.OpGenOverride.AttrDefault)
    ))
  ,

  Rename = _reflection.GeneratedProtocolMessageType('Rename', (_message.Message,), dict(
    DESCRIPTOR = _OPGENOVERRIDE_RENAME,
    __module__ = 'tensorflow.core.framework.op_gen_overrides_pb2'
    # @@protoc_insertion_point(class_scope:tensorflow.OpGenOverride.Rename)
    ))
  ,
  DESCRIPTOR = _OPGENOVERRIDE,
  __module__ = 'tensorflow.core.framework.op_gen_overrides_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.OpGenOverride)
  ))
_sym_db.RegisterMessage(OpGenOverride)
_sym_db.RegisterMessage(OpGenOverride.AttrDefault)
_sym_db.RegisterMessage(OpGenOverride.Rename)

OpGenOverrides = _reflection.GeneratedProtocolMessageType('OpGenOverrides', (_message.Message,), dict(
  DESCRIPTOR = _OPGENOVERRIDES,
  __module__ = 'tensorflow.core.framework.op_gen_overrides_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.OpGenOverrides)
  ))
_sym_db.RegisterMessage(OpGenOverrides)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
