apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metastore-2-1-1
  labels:
    app: metastore-2-1-1
    version: 2.1.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metastore-2-1-1
  template:
    metadata:
      labels:
        app: metastore-2-1-1
    spec:
      containers:
      - name: metastore-2-1-1
        image: docker.io/fluxcapacitor/metastore-2.1.1:master
        resources:
          limits:
            cpu: 5000m
            memory: 5000Mi
          requests:
            cpu: 1000m
            memory: 1000Mi
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 9083
        volumeMounts:
          - name: metastore-config-volume
            mountPath: /root/apache-hive-2.1.1-bin/conf
      volumes:
        - name: metastore-config-volume
          configMap:
            name: metastore-config
