apiVersion: v1
kind: ReplicationController
metadata:
  name: metastore-1-2-1
  labels:
    app: metastore
    version: 1.2.1
spec:
  replicas: 1
  selector:
    name: metastore-1-2-1
  template:
    metadata:
      labels:
        name: metastore-1-2-1
    spec:
      containers:
      - name: metastore-1-2-1
        image: docker.io/fluxcapacitor/metastore-1.2.1
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 9083
