/*
 *
 * FunctionPage constants
 *
 */

export const LOAD_FUNCTIONS_REQUEST = 'app/Functions/LOAD_FUNCTIONS_REQUEST';
export const LOAD_FUNCTIONS_SUCCESS = 'app/Functions/LOAD_FUNCTIONS_SUCCESS';
export const LOAD_FUNCTIONS_ERROR = 'app/Functions/LOAD_FUNCTIONS_ERROR';
export const CREATE_FUNCTION_REQUEST = 'app/Functions/CREATE_FUNCTION_REQUEST';
export const CREATE_FUNCTION_SUCCESS = 'app/Functions/CREATE_FUNCTION_SUCCESS';
export const CREATE_FUNCTION_ERROR = 'app/Functions/CREATE_FUNCTION_ERROR';
export const UPLOAD_FUNCTIONS_IN_BATCH_REQUEST = 'app/Functions/UPLOAD_FUNCTIONS_IN_BATCH_REQUEST';
export const UPLOAD_SINGLE_FUNCTION_IN_BATCH_PROGRESS = 'app/Functions/UPLOAD_SINGLE_FUNCTION_IN_BATCH_PROGRESS';
export const UPLOAD_SINGLE_FUNCTION_IN_BATCH_ERROR = 'app/Functions/UPLOAD_SINGLE_FUNCTION_IN_BATCH_ERROR';
export const SET_UPLOAD_FUNCTIONS = 'app/Functions/SET_UPLOAD_FUNCTIONS';
export const DELETE_FUNCTION_REQUEST = 'app/Functions/DELETE_FUNCTION_REQUEST';
export const DELETE_FUNCTION_SUCCESS = 'app/Functions/DELETE_FUNCTION_SUCCESS';
export const DELETE_FUNCTION_ERROR = 'app/Functions/DELETE_FUNCTION_ERROR';
export const GET_FUNCTION_REQUEST = 'app/Functions/GET_FUNCTION_REQUEST';
export const GET_FUNCTION_SUCCESS = 'app/Functions/GET_FUNCTION_SUCCESS';
export const GET_FUNCTION_ERROR = 'app/Functions/GET_FUNCTION_ERROR';
export const UPDATE_FUNCTION_REQUEST = 'app/Functions/UPDATE_FUNCTION_REQUEST';
export const UPDATE_FUNCTION_SUCCESS = 'app/Functions/UPDATE_FUNCTION_SUCCESS';
export const UPDATE_FUNCTION_ERROR = 'app/Functions/UPDATE_FUNCTION_ERROR';
export const TEST_FUNCTION_REQUEST = 'app/Functions/TEST_FUNCTION_REQUEST';
export const TEST_FUNCTION_SUCCESS = 'app/Functions/TEST_FUNCTION_SUCCESS';
export const TEST_FUNCTION_ERROR = 'app/Functions/TEST_FUNCTION_ERROR';
export const CLEAN_TEST_FUNCTION_REQUEST = 'app/Functions/CLEAN_TEST_FUNCTION_REQUEST';

export const LOAD_TRIGGERSHTTP_REQUEST = 'app/Functions/LOAD_TRIGGERSHTTP_REQUEST';
export const LOAD_TRIGGERSHTTP_SUCCESS = 'app/Functions/LOAD_TRIGGERSHTTP_SUCCESS';
export const LOAD_TRIGGERSHTTP_ERROR = 'app/Functions/LOAD_TRIGGERSHTTP_ERROR';
export const DELETE_TRIGGERHTTP_REQUEST = 'app/Functions/DELETE_TRIGGERSHTTP_REQUEST';
export const DELETE_TRIGGERHTTP_SUCCESS = 'app/Functions/DELETE_TRIGGERSHTTP_SUCCESS';
export const DELETE_TRIGGERHTTP_ERROR = 'app/Functions/DELETE_TRIGGERSHTTP_ERROR';
export const CREATE_TRIGGERHTTP_REQUEST = 'app/Functions/CREATE_TRIGGERSHTTP_REQUEST';
export const CREATE_TRIGGERHTTP_SUCCESS = 'app/Functions/CREATE_TRIGGERSHTTP_SUCCESS';
export const CREATE_TRIGGERHTTP_ERROR = 'app/Functions/CREATE_TRIGGERSHTTP_ERROR';

export const LOAD_KUBEWATCHERS_REQUEST = 'app/Functions/LOAD_KUBEWATCHERS_REQUEST';
export const LOAD_KUBEWATCHERS_SUCCESS = 'app/Functions/LOAD_KUBEWATCHERS_SUCCESS';
export const LOAD_KUBEWATCHERS_ERROR = 'app/Functions/LOAD_KUBEWATCHERS_ERROR';
export const DELETE_KUBEWATCHER_REQUEST = 'app/Functions/DELETE_KUBEWATCHER_REQUEST';
export const DELETE_KUBEWATCHER_SUCCESS = 'app/Functions/DELETE_KUBEWATCHER_SUCCESS';
export const DELETE_KUBEWATCHER_ERROR = 'app/Functions/DELETE_KUBEWATCHER_ERROR';
export const CREATE_KUBEWATCHER_REQUEST = 'app/Functions/CREATE_KUBEWATCHER_REQUEST';
export const CREATE_KUBEWATCHER_SUCCESS = 'app/Functions/CREATE_KUBEWATCHER_SUCCESS';
export const CREATE_KUBEWATCHER_ERROR = 'app/Functions/CREATE_KUBEWATCHER_ERROR';
