FROM fluxcapacitor/package-ubuntu-16.04:master

ENV KUBERNETES_VERSION=1.6.2

WORKDIR /root

RUN \
  wget https://storage.googleapis.com/kubernetes-release/release/v$KUBERNETES_VERSION/bin/linux/amd64/kubectl

RUN \
  sudo chmod a+x kubectl \
  && sudo mv kubectl /usr/local/bin/kubectl

RUN \
  mkdir -p ~/.kube

RUN \
  pip install pio-cli==0.32
