#!/bin/bash

export CLASSPATH=$(${HADOOP_HDFS_HOME}/bin/hadoop classpath --glob)

python bin/dist_mnist_trainer.py \
  --ps_hosts=$PS_HOSTS \
  --worker_hosts=$WORKER_HOSTS \
  --job_name=$JOB_NAME \
  --task_index=$TASK_INDEX
