#!/bin/bash

start_model_training_tensorflow() {
    echo "PIO_MODEL_PATH=$PIO_MODEL_PATH"
    echo "PIO_MODEL_TYPE=$PIO_MODEL_TYPE"
    echo "PIO_MODEL_NAME=$PIO_MODEL_NAME"

    echo ""
    echo "Starting TensorFlow-based Model Training..."
    echo ""

    source activate $PIO_CONDA_ENV_NAME 

    cd $PIO_MODEL_PATH \
    guild prepare 
    guild train
    guild view 
    cd /root
}

start_model_training_python3() {
    echo "PIO_MODEL_PATH=$PIO_MODEL_PATH"
    echo "PIO_MODEL_TYPE=$PIO_MODEL_TYPE"
    echo "PIO_MODEL_NAME=$PIO_MODEL_NAME"

    echo ""
    echo "Starting Python-based Model Training..."
    echo ""

    source activate $PIO_CONDA_ENV_NAME

    cd $PIO_MODEL_PATH \
    python pio_train.py
    echo ""
    echo "...Training Complete!"
    echo ""
    cd /root
}

source sysutils/container-limits.sh

echo "Required Environment Variables..."
echo "PIO_MODEL_PATH=$PIO_MODEL_PATH"
echo "PIO_MODEL_TYPE=$PIO_MODEL_TYPE"
echo "PIO_MODEL_NAME=$PIO_MODEL_NAME"

if [[ $PIO_MODEL_TYPE == "python3" ]] ||
   [[ $PIO_MODEL_TYPE == "keras" ]] ||
   [[ $PIO_MODEL_TYPE == "scikit" ]]; then

  start_model_training_python3
fi;

if [[ $PIO_MODEL_TYPE == "tensorflow" ]]; then
  start_model_training_tensorflow
fi;
