apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
spec:
  type: NodePort 
  ports:
  - name: hdfs-native
    port: 9000
    targetPort: 9000
  - name: hdfs-webui
    port: 50070
    targetPort: 50070
  selector:
    name: hdfs-namenode
