apiVersion: v1
kind: Service
metadata:
  name: hdfs
spec:
  type: LoadBalancer 
  ports:
  - name: hdfs-native
    port: 9000
    targetPort: 9000
  - name: hdfs-webui
    port: 80 
    targetPort: 50070
  - name: hue-webui
    port: 8000
    targetPort: 8000
  selector:
    name: hdfs
