apiVersion: v1
kind: ReplicationController
metadata:
  name: hdfs
  labels:
    app: hdfs
    version: 2.7.2
spec:
  replicas: 1
  selector:
    name: hdfs
  template:
    metadata:
      labels:
        name: hdfs
    spec:
      containers:
      - name: hdfs
        image: docker.io/fluxcapacitor/hdfs:v1.0.0
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 8000
        - containerPort: 9000
        - containerPort: 50070
      nodeSelector:
        training: "true"
