apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hdfs-namenode
  labels:
    app: hdfs-namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdfs-namenode
  template:
    metadata:
      labels:
        app: hdfs-namenode
    spec:
      containers:
      - name: hdfs-namenode
        image: docker.io/fluxcapacitor/hdfs-namenode:master
        resources:
          limits:
            cpu: 1000m
            memory: 5000Mi
          requests:
            cpu: 100m
            memory: 500Mi
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 8000
        - containerPort: 9000
        - containerPort: 50070
        volumeMounts:
          - name: hdfs-config-volume
            mountPath: /root/hadoop-2.7.2/etc/hadoop
          - name: git-volume
            mountPath: /root/volumes
      volumes:
        - name: hdfs-config-volume
          configMap:
            name: hdfs-config
        - name: git-volume
          gitRepo:
            repository: "https://github.com/fluxcapacitor/source.ml"
            revision: "master"
