#!/bin/bash

# Must be fully-qualified path
/usr/sbin/sshd

#cd hue-3.12.0 && ./build/env/bin/hue runserver 0.0.0.0:8000 &
 
cd ~ && start-dfs.sh

tail -f $HADOOP_HOME/logs/hadoop-$(whoami)-namenode-$HOSTNAME.log
