#!/bin/bash

/usr/local/bin/dockerd

mysql --host=sql-mysql-master --port=3306 --user=root --password=password -e "CREATE DATABASE IF NOT EXISTS airflow"
sleep 2

# TODO:  Don't re-init upon process restart
airflow initdb
sleep 2 

# TODO:  Separate these out into separate containers - perhaps in same pod
airflow flower &

airflow webserver &

airflow worker &

airflow scheduler 
