apiVersion: v1
kind: Pod
metadata:
  name: doppelganger-train
  namespace: deployment
  labels:
    app: doppelganger-train
    type: training
    framework: tensorflow
spec:
  restartPolicy: OnFailure
  containers:
  - name: doppelganger-train
    image: antjebarth/doppelganger-train:1.0.0 
    imagePullPolicy: Always
    command:
      - "python"
      - "doppelganger-train.py"
#    env:
#      - name: AWS_REGION
#        value: eu-central-1
