apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jupyterhub
  labels:
    app: jupyterhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterhub
  template:
    metadata:
      labels:
        app: jupyterhub
    spec:
      containers:
      - name: jupyterhub
        image: docker.io/fluxcapacitor/jupyterhub:master
        resources:
          limits:
            cpu: 4000m
            memory: 4000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: SPARK_MASTER
          value: spark://spark-master-2-1-0:7077
        - name: SPARK_SUBMIT_ARGS
          value: ""
        - name: JUPYTERHUB_AUTHENTICATOR
          value: dummyauthenticator.DummyAuthenticator 
        - name: OAUTH_CALLBACK_URL
          value: "" 
        - name: OAUTH_CLIENT_ID
          value: ""
        - name: OAUTH_CLIENT_SECRET
          value: ""
        ports:
        - containerPort: 6006
        - containerPort: 8754
        - containerPort: 8755
