#!/bin/bash

# All paths (dirs, not files) up to and including /root must have +x permissions.
# It's just the way linux works.  Don't fight it.
# http://askubuntu.com/questions/537032/how-to-configure-apache2-with-symbolic-links-in-var-www
if [ ! -f /var/www/html ]; then
  chmod a+x /root
  cd /var/www/ && ln -s /root/html
fi

if [ ! -f /etc/apache2/apache2.conf ]; then
  cd /etc/apache2/ && ln -s /root/config/apache2/apache2.conf
fi

if [ ! -f /etc/apache2/sites-available/www.conf ]; then
  cd /etc/apache2/sites-available && ln -s /root/config/apache2/www.conf
  a2ensite www.conf
fi

source /etc/apache2/envvars

service apache2 start

source /root/sysutils/container-limits.sh

export JAVA_MAX_MEM_RATIO=85
export JAVA_OPTIONS="$(/root/sysutils/jvm-limits.sh)"

#$SPARK_HOME/sbin/start-master.sh --webui-port 6060
#$SPARK_HOME/sbin/start-slave.sh --cores 4 --memory 4g --webui-port 6061 spark://127.0.0.1:7077

/usr/sbin/sshd
cd ~
start-dfs.sh &

cd ~
tensorboard --host=0.0.0.0 --logdir=/root/tensorboard &

cd ~
export CLASSPATH=$(${HADOOP_HDFS_HOME}/bin/hadoop classpath --glob)
CLASSPATH=$CLASSPATH jupyterhub --ip='' --config=config/jupyterhub/jupyterhub_config.py 2>&1 > /root/logs/tensorflow-jupyterhub.out
