apiVersion: v1 
kind: Service
metadata:
  name: jupyterhub
spec:
  type: LoadBalancer
  ports:
  - name: jupyterhub
    port: 80 
    targetPort: 8754
  - name: tensorboard
    port: 6006
    targetPort: 6006
  selector:
    name: jupyterhub
