apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jupyterhub-master
  labels:
    app: jupyterhub-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterhub-master
  template:
    metadata:
      labels:
        app: jupyterhub-master
    spec:
      containers:
      - name: jupyterhub-master
        image: docker.io/fluxcapacitor/jupyterhub
        resources:
          limits:
            cpu: 400m
            memory: 1200Mi
          requests:
            cpu: 100m
            memory: 300Mi
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: SPARK_MASTER
          value: spark://spark-master-2-1-0:7077
        - name: SPARK_SUBMIT_ARGS
          value: "--conf spark.cores.max=2 --conf spark.executor.memory=2g --conf spark.cassandra.connection.host=cassandra --packages com.amazonaws:aws-java-sdk:1.7.4,org.apache.hadoop:hadoop-aws:2.7.1,com.datastax.spark:spark-cassandra-connector_2.11:2.0.0-M3,com.databricks:spark-avro_2.11:3.0.1 --jars /root/lib/jpmml-sparkml-package-1.0-SNAPSHOT.jar --py-files /root/lib/jpmml.py"
        ports:
        - containerPort: 6006
        - containerPort: 8754
        volumeMounts:
          - name: kube-config-secret-volume
            readOnly: true
            mountPath: /root/.kube
          - name: hadoop-conf-dev-volume
            mountPath: /etc/hadoop/conf
          - name: git-volume
            mountPath: /root/volumes
      volumes:
        - name: kube-config-secret-volume
          secret:
            secretName: kube-config-secret
        - name: hadoop-conf-dev-volume
          secret:
            secretName: hadoop-conf-dev
        - name: git-volume
          gitRepo:
            repository: "https://github.com/fluxcapacitor//source.ml"
            revision: "master"
      imagePullSecrets:
        - name: githubsshkey
#      nodeSelector:
#        training: "true"
