#!/bin/bash

if [ ! -f ~/notebooks ]; then
  cd ~ && ln -s /root/volumes/source.ml/jupyterhub.ml/notebooks
fi

if [ ! -f ~/lib ]; then
  cd ~ && ln -s /root/volumes/source.ml/jupyterhub.ml/lib
fi

if [ ! -f ~/datasets ]; then
  cd ~ && ln -s /root/volumes/source.ml/jupyterhub.ml/datasets
fi

if [ ! -f ~/scripts ]; then
  cd ~ && ln -s /root/volumes/source.ml/jupyterhub.ml/scripts
fi

if [ ! -f ~/src ]; then
  cd ~ && ln -s /root/volumes/source.ml/jupyterhub.com/src
fi

if [ ! -f ~/tests ]; then
  cd ~ && ln -s /root/volumes/source.ml/jupyterhub.com/tests
fi

# All paths (dirs, not files) up to and including /root must have +x permissions.
# It's just the way linux works.  Don't fight it.
# http://askubuntu.com/questions/537032/how-to-configure-apache2-with-symbolic-links-in-var-www
if [ ! -f /var/www/html ]; then
  chmod a+x /root
  cd /var/www/ && ln -s /root/html
fi

if [ ! -f /etc/apache2/apache2.conf ]; then
  cd /etc/apache2/ && ln -s /root/config/apache2/apache2.conf
fi

if [ ! -f /etc/apache2/sites-available/www.conf ]; then
  cd /etc/apache2/sites-available && ln -s /root/config/apache2/www.conf
  a2ensite www.conf
fi

source /etc/apache2/envvars

service apache2 start

export CLASSPATH=$(${HADOOP_HDFS_HOME}/bin/hadoop classpath --glob)

source sysutils/container-limits.sh

export JAVA_MAX_MEM_RATIO=85
export JAVA_OPTIONS="$(sysutils/jvm-limits.sh)"

cd ~
tensorboard --host=0.0.0.0 --logdir=/root/tensorboard &

cd ~
jupyterhub --ip='' --config=config/jupyterhub/jupyterhub_config.py
