#!/bin/bash

# Required by Tensorflow for HDFS
export CLASSPATH=$(${HADOOP_HDFS_HOME}/bin/hadoop classpath --glob)

cd ~
tensorboard --host=0.0.0.0 --logdir=/root/tensorboard &

cd ~ 
jupyterhub --ip='' --config=config/jupyterhub/jupyterhub_config.py
