apiVersion: v1
kind: ReplicationController
metadata:
  name: web-home
  labels:
    app: web-home
spec:
  replicas: 1
  selector:
    name: web-home
  template:
    metadata:
      labels:
        name: web-home
    spec:
      containers:
      - name: web-home
        image: docker.io/fluxcapacitor/web-home:v1.0.0
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 80
        volumeMounts:
          - name: git-volume
            mountPath: /root/volumes
      volumes:
        - name: git-volume
          gitRepo:
            repository: "https://github.com/fluxcapacitor/source.ml.git"
            revision: "v1.0.0"
      nodeSelector:
        training: "true"
