apiVersion: v1
kind: ReplicationController
metadata:
  name: web-sparkafterdark
  labels:
    app: web-sparkafterdark
spec:
  replicas: 1
  selector:
    name: web-sparkafterdark
  template:
    metadata:
      labels:
        name: web-sparkafterdark
    spec:
      containers:
      - name: web-sparkafterdark
        image: docker.io/fluxcapacitor/web-sparkafterdark
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 80
        volumeMounts:
          - name: git-volume
            mountPath: /root/volumes
      volumes:
        - name: git-volume
          gitRepo:
            repository: "https://github.com/fluxcapacitor/source.ml.git"
            revision: "master"
      imagePullSecrets:
        - name: githubsshkey
      nodeSelector:
        training: "true"
