#!/usr/bin/env bash

# pull latest from github!
pull_force_overwrite_local

cd ~
tensorboard --host=0.0.0.0 --logdir=/root/tensorboard &

cd ~
$SPARK_HOME/sbin/start-master.sh --webui-port 6060
$SPARK_HOME/sbin/start-slave.sh --cores 4 --memory 4g --webui-port 6061 spark://127.0.0.1:7077

/usr/sbin/sshd

cd ~ 
start-dfs.sh &

if [ ! -f /var/www/html ]; then
  cd /var/www/ && ln -s /root/html
fi

if [ ! -f /etc/apache2/apache2.conf ]; then
  cd /etc/apache2/ && ln -s /root/config/apache2/apache2.conf
fi

if [ ! -f /etc/apache2/sites-available/www.conf ]; then
  cd /etc/apache2/sites-available && ln -s /root/config/apache2/www.conf
fi

a2ensite www.conf

source /etc/apache2/envvars

service apache2 start

cd ~
export CLASSPATH=$(${HADOOP_HDFS_HOME}/bin/hadoop classpath --glob)
CLASSPATH=$CLASSPATH jupyterhub --ip='' --config=config/jupyterhub/jupyterhub_config.py 2>&1 > /root/logs/tensorflow-jupyterhub.out
