#!/bin/bash

if [ ! -f ~/lib ]; then
  cd ~ && ln -s /root/volumes/source.ml/zeppelin.ml/lib
fi

if [ ! -f ~/notebook ]; then
  cd ~ && ln -s /root/volumes/source.ml/zeppelin.ml/notebook
fi

# Note:  The port must be set here as a localized env variable, 
#   otherwise Zeppelin picks the Kubernetes-injected value
#   that includes a full "tcp://<host>:<port>" type of url
ZEPPELIN_PORT=3123 MASTER=$SPARK_MASTER $ZEPPELIN_HOME/bin/zeppelin.sh start
