#!/bin/bash

if [ ! -f ~/lib ]; then
  cd ~ && ln -s /root/volumes/source.ml/zeppelin.ml/lib
fi

if [ ! -f ~/notebook ]; then
  cd ~ && ln -s /root/volumes/source.ml/zeppelin.ml/notebook
fi

MASTER=$SPARK_MASTER $ZEPPELIN_HOME/bin/zeppelin.sh start
