apiVersion: v1
kind: Service
metadata:
  name: zeppelin
  labels:
    app: zeppelin
  annotations:
    dns.alpha.kubernetes.io/external: zeppelin.your.domain.com
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 80 
    targetPort: 3123 
  - name: "websocket"
    port: 81 
    targetPort: 3124
  selector:
    app: zeppelin
