#!/bin/bash

$CONFLUENT_HOME/bin/kafka-server-start -daemon $CONFLUENT_HOME/etc/kafka/server.properties --override zookeeper.connect=zookeeper:2181

#sleep 5
#$CONFLUENT_HOME/bin/schema-registry-start -daemon $CONFLUENT_HOME/etc/schema-registry/schema-registry.properties

sleep 5
$CONFLUENT_HOME/bin/kafka-topics --zookeeper zookeeper:2181 --create --topic $TOPIC_NAME --partitions $NUM_PARTITIONS --replication-factor $NUM_REPLICAS

#sleep 5
#$CONFLUENT_HOME/bin/kafka-rest-start -daemon $CONFLUENT_HOME/etc/kafka-rest/kafka-rest.properties

tail -f $CONFLUENT_HOME/logs/server.log
