apiVersion: v1
kind: ReplicationController
metadata:
  name: apachespark-master-2-1-0
  labels:
    name: apachespark-master-2-1-0
spec:
  replicas: 1
  selector:
    name: apachespark-master-2-1-0
  template:
    metadata:
      labels:
        name: apachespark-master-2-1-0
    spec:
      containers:
      - name: apachespark-master-2-1-0
        image: docker.io/fluxcapacitor/apachespark-master-2.1.0:master
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 6060
        - containerPort: 6066
        - containerPort: 7077
        - containerPort: 4040
        - containerPort: 4041
        - containerPort: 4042
        - containerPort: 4043
        - containerPort: 4044
