apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apachespark-master-2-1-0
  labels:
    app: apachespark-master-2-1-0
    role: master
    version: 2.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apachespark-master-2-1-0
  template:
    metadata:
      labels:
        app: apachespark-master-2-1-0
    spec:
      containers:
      - name: apachespark-master-2-1-0
        image: docker.io/fluxcapacitor/apachespark-master-2.1.0:master
        resources:
          limits:
            cpu: 4000m
            memory: 4000Mi
          requests:
            cpu: 1000m
            memory: 1000Mi
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 6060
        - containerPort: 6066
        - containerPort: 7077
        - containerPort: 4040
        - containerPort: 4041
        - containerPort: 4042
        - containerPort: 4043
        - containerPort: 4044
        volumeMounts:
          - name: hdfs-config-volume
            mountPath: /root/hadoop-2.7.2/etc/hadoop
          - name: spark-config-volume
            mountPath: /root/spark-2.1.0-bin-fluxcapacitor/conf
      volumes:
        - name: hdfs-config-volume
          configMap:
            name: hdfs-config
        - name: spark-config-volume
          configMap:
            name: spark-config